### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice-r#15]
Subsequent queries might exhaust the rate limit of [40 requests/min](https://openrouteservice.org/plans/), as in the following example. Consider implementing a [limiting mechanism](https://cran.r-project.org/web/packages/httr/vignettes/api-packages.html#rate-limiting).

```r
replicate(100, ors_geocode("Heidelberg"))
## Error: openrouteservice API request failed
##   [429] Rate limit exceeded 
```

**Comment by aoles** [comment]
Even though the user doesn't have access to the remaining per minute usage limit, we can just check for "Error 429" and pool the api say every second until it starts working again.

**Comment by TimMcCauley** [comment]
Gj !
