### ISSUE TITLE
Specify countries by names

### ISSUE THREAD

**Issue by aoles** [GIScience/openrouteservice-r#36]
Allow providing countries to advanced routing `options` by names rather than obscure ORS country codes. Maybe [countrycode](https://CRAN.R-project.org/package=countrycode) package with ORS country codes added as data source could be levereged for this.

**Comment by aoles** [comment]
[countrycode](https://cran.r-project.org/package=countrycode) looks really promising for this purpose as it allows quite a lot of flexibility in specifying the names.

```r
library(countrycode)

countrycode(c("Great Britain",
              "United Kingdom",
              "United States of America",
              "USA"), "country.name", "iso2c")

## [1] "GB" "GB" "US" "US"
```

**Comment by cjyetman** [comment]
If you have a link to an "official", machine readable list of ORS country codes along with what they represent, we could probably add it to [countrycode](https://github.com/vincentarelbundock/countrycode).

**Comment by aoles** [comment]
Resolved via https://github.com/GIScience/openrouteservice/pull/390.
