### ISSUE TITLE
submit location via dataframe

### ISSUE THREAD

**Issue by aghaynes** [GIScience/openrouteservice-r#38]
I would like to suggest an improvement. How about allowing user to submit a dataframe/matrix rather than a list (as done in the osmdata package for instance)? It would improve usability tremendously...

Thanks,

Alan

**Comment by aoles** [comment]
Hi Alan,

many thanks for your feedback, sounds like a reasonable idea! In fact, `ors_matrix` function already accepts a two-column data frame as input for `locations`. Please feel free to give it a try and let me briefly know whether this works for you as desired. I could then implement a similar feature for the rest of the api functions.

Cheers,
Andrzej

**Comment by aghaynes** [comment]
That's exactly what I had in mind!! (once I'd updated to the newer version :)) 👍 

Thanks!!
Alan
