### ISSUE TITLE
Calling a locally hosted instance of ors fails

### ISSUE THREAD

**Issue by mawds** [GIScience/openrouteservice-r#46]
I'm unable to call a locally hosted instance of openrouteservice (created following the instructions [here](https://github.com/GIScience/openrouteservice/tree/master/docker)) from openrouteservice-r

I'm setting the endpoint using ` options("openrouteservice.url"="http://localhost:8080/ors/")`.  Setting the `openrouteservice.verbose` option shows that the `/ors/` is being stripped from the URLs, so all calls fail.  

This is because the call to `modify_url()` in `api_call.R` _replaces_ the path element of the URL, and so loses the `/ors/`.  I've fixed this locally by pasting any existing path element of `ors_url()` to `path`.  I'm unsure whether this is the best approach to fixing it - I'm happy to submit a PR if you think that's an OK way of fixing it.

**Comment by aoles** [comment]
Dear David,

thank you for reporting the problem.

I will look into possible improvements, in the meantime try the following:

```r
options(openrouteservice.url = "http://localhost:8080")
options(openrouteservice.paths = list(directions = "ors/routes"))
```

Cheers,
Andrzej

**Comment by mawds** [comment]
Thanks Andrzej - that works (adding `matrix = "ors/matrix"` for distance matrices etc).  

If you're happy with the approach I took in the commit to my fork I can turn that into a PR.  I just wasn't sure if it was a good way of dealing with it.

David

**Comment by aoles** [comment]
Thank you David,

let me review your changes first, I will get back to you regarding the PR.

Cheers,
Andrzej
