### ISSUE TITLE
ors_isochrones to sf

### ISSUE THREAD

**Issue by EricKrg** [GIScience/openrouteservice-r#5]
Hey I am using your package for my shiny-app and i use this conversion function to convert the ors objects to sf, maybe this is useful and could be implemented in the package (i could also contribute this for the other geom types):
```r
require(sf)

iso2sf = function(obj){
  k = 1
  poly_list = list()
  for (i in obj$features){
    tmp = i
    tmp2 = data.frame(lon = 0, lat = 0)
    n = 1
    for(j in tmp$geometry$coordinates[[1]]){
      tmp2 = rbind(tmp2, c(lon = j[1], lat = j[2]))
      n = n + 1
    }
    interval[k] = tmp$properties$value
    poly_list[[k]] = sf::st_sfc(st_polygon(list(as.matrix(tmp2)[-1,])),  
                             crs = 4326)
    k = k + 1
  }
  
  polys = do.call(c,rev(poly_list))
  p = sf::st_sf(interval = rev(interval) ,geometry =  polys)
  return(p)
}

# test calls
#
# iso <- ors_isochrones(geo_code("Jena"),range =1000 ,interval = 200,range_type = "distance")
# iso2sf(iso)
```

**Comment by EricKrg** [comment]
Hey Andrzej,

sorry that the frist one wasnt reproducible, here is a better version: 

i am currently using the geo_code function from the st_planr package, but this could be easily changed to your internal geocode function.

I hope this version works for you.
```r 
require(sf)
require(stplanr)
require(openrouteservice)

iso2sf = function(obj){
  interval = c()
  k = 1
  poly_list = list()
  for (i in obj$features){
    tmp = i
    tmp2 = data.frame(lon = 0, lat = 0)
    n = 1
    for(j in tmp$geometry$coordinates[[1]]){
      tmp2 = rbind(tmp2, c(lon = j[1], lat = j[2]))
      n = n + 1
    }
    interval[k] = tmp$properties$value
    poly_list[[k]] = sf::st_sfc(st_polygon(list(as.matrix(tmp2)[-1,])),  
                                crs = 4326)
    k = k + 1
  }
  
  polys = do.call(c,rev(poly_list))
  p = sf::st_sf(interval = rev(interval) ,geometry =  polys)
  return(p)
}


# test calls
#
# iso <- ors_isochrones(stplanr::geo_code("Jena"),range =1000 ,interval = 200,range_type = "distance")
# iso_sf <- iso2sf(iso)
# mapview::mapview(iso_sf)
```
PS.: i am traveling this week, but i try to respond as soon as i can to your comments.

Cheers, 
Eric

**Comment by aoles** [comment]
Thanks a lot for the updated example, it works now fine for me.

The isochrones API response is in fact structured as a valid GeoJSON object so in principle it should be possible to leverage some existing R packages to handle the conversion to sf, such as [geojsonsf](https://CRAN.R-project.org/package=geojsonsf). For some reason, however, `geojsonsf::geojson_sf` gives a quite different output than your conversion function. Not sure why though, I will need to look into this. Maybe the developer of geojsonsf @SymbolixAU has some additional comments on this.

```r
library(openrouteservice)
coordinates <- ors_geocode("Jena")$features[[1]]$geometry$coordinates
iso <- ors_isochrones(coordinates, range = 1000, interval = 200, range_type = "distance")
iso_gj <- toJSON(iso, auto_unbox = TRUE)

library(geojsonsf)
iso_sf <- geojson_sf(iso_gj)

mapview::mapview(iso_sf)
## Warning message:
## In is.na(x) : is.na() applied to non-(list or vector) of type 'NULL'
```

**Comment by SymbolixAU** [comment]
@EricKrg @aoles 

I think both methods produce the same result (apart from the order of polygons)

```
coordinates <- ors_geocode("Jena")$features[[1]]$geometry$coordinates
iso <- ors_isochrones(coordinates, range = 1000, interval = 200, range_type = "distance")

iso_gj <- jsonlite::toJSON(iso, auto_unbox = TRUE)

iso2sf = function(obj){
  interval = c()
  k = 1
  poly_list = list()
  for (i in obj$features){
    tmp = i
    tmp2 = data.frame(lon = 0, lat = 0)
    n = 1
    for(j in tmp$geometry$coordinates[[1]]){
      tmp2 = rbind(tmp2, c(lon = j[1], lat = j[2]))
      n = n + 1
    }
    interval[k] = tmp$properties$value
    poly_list[[k]] = sf::st_sfc(st_polygon(list(as.matrix(tmp2)[-1,])),  
                                crs = 4326)
    k = k + 1
  }
  
  polys = do.call(c,rev(poly_list))
  p = sf::st_sf(interval = rev(interval) ,geometry =  polys)
  return(p)
}

sf <- geojsonsf::geojson_sf(iso_gj)
sf_iso <- iso2sf(iso)


library(googleway)

set_key("GOOGLE_MAP_KEY")

google_map() %>%
  add_polygons(sf)
```

![screen shot 2018-04-26 at 8 03 38 am](https://user-images.githubusercontent.com/18344164/39275418-8582060a-4928-11e8-87f2-154ab31a972b.png)


```
google_map() %>%
  add_polygons(sf_iso)
```

![screen shot 2018-04-26 at 8 03 44 am](https://user-images.githubusercontent.com/18344164/39275420-89086238-4928-11e8-92fe-adcc033d9bf0.png)

**Comment by SymbolixAU** [comment]
Could I also suggest an option to return the raw JSON/GeoJSON from the `api_call`? 

I.e., define the query in https://github.com/GIScience/openrouteservice-r/blob/master/R/isochrones.R#L23 as per usual
```
query = list(locations = coordinates, profile = "driving-car", range = 1000, interval = 200, range_type = "distance")

url <- httr::modify_url(url = getOption('openrouteservice.url'),
                  path = "isochrones",
                  query = openrouteservice:::api_query(query, collapse=collapse))
```

Then have an option here https://github.com/GIScience/openrouteservice-r/blob/master/R/api_call.R#L48 to return just JSON/GeoJSON?

```
geo <- readLines(url)

## If `return_geo` == TRUE, return(geo)
 res <- do.call(method, list(url, accept_json(), user_agent("openrouteservice-r"), ...))
```

This would mean you can bypass some of the internal `toJSON/fromJSON` calls.

**Comment by aoles** [comment]
Thanks a lot @SymbolixAU for all your comments. I've moved your suggestion to a separate issue to better keep track of it.

Does anyone have an idea why the rendered polygons show up with different color scheme?

```r
library(openrouteservice)

coordinates <- ors_geocode("Jena")$features[[1]]$geometry$coordinates
iso <- ors_isochrones(coordinates, range = 1000, interval = 200, range_type = "distance")
iso_gj <- jsonlite::toJSON(iso, auto_unbox = TRUE)

sf <- geojsonsf::geojson_sf(iso_gj)
sf <- sf[dim(sf)[1]:1,]
mapview::mapview(sf)
```
![sf](https://user-images.githubusercontent.com/6545356/39315334-be5a9390-4976-11e8-98b9-d758ab644361.png)

```r
sf_iso <- iso2sf(iso)
mapview::mapview(sf_iso)
```
![sf_iso](https://user-images.githubusercontent.com/6545356/39315346-c35fbe56-4976-11e8-8fbc-a3d00444c1cc.png)

**Comment by SymbolixAU** [comment]
@aoles 

it's to do with which values are included in the `sf` object, and therefore which are recognised by `mapview`

try

```
mapview::mapview(sf[nrow(sf):1, c("value")])
```

**Comment by aoles** [comment]
@SymbolixAU thanks a lot for clarifying!

**Comment by aoles** [comment]
@EricKrg As of version 0.1.5 it should be possible to get an unparsed GeoJSON string with `parse_output = FALSE` which can be readily converted to an sf object with `geojson_sf`, as in the example below.

```r
require(openrouteservice)
require(geojsonsf)

coordinates <- ors_geocode("Jena")$features[[1]]$geometry$coordinates
iso <- ors_isochrones(coordinates, range = 1000, interval = 200, range_type = "distance",
                                   parse_output = FALSE)
sf <- geojson_sf(iso)

## reverse polygon order and select interval value
sf <- sf[nrow(sf):1, "value"]

mapview::mapview(sf)
```

**Comment by EricKrg** [comment]
@aoles, this works fine for me! Great enhancement, i will close the issue if this is allrigth?

**Comment by aoles** [comment]
Dear @EricKrg, @SymbolixAU,

I'm happy to announce that after some recent updates it is now possible to work directly with simple feature output like so:

```r
require(openrouteservice)
require(sf)

coordinates <- st_coordinates(ors_geocode("Jena", size = 1, output = "sf"))

sf <- ors_isochrones(coordinates, range = 1000, interval = 200, range_type = "distance",
                     output = "sf")

## reverse polygon order and select interval value for plotting
sf <- sf[nrow(sf):1, "value"]

mapview::mapview(sf)
```
