### ISSUE TITLE
Geocode - boundary.country

### ISSUE THREAD

**Issue by bartekbursa** [GIScience/openrouteservice-r#59]
Is there any way to specify more than one boundary country in the `ors_geocode()` ? Will it accept a vector with many country codes?

Cheers
Bartosz

**Comment by aoles** [comment]
ors_geocode("Heidelberg", boundary.country = "DE")

**Comment by bartekbursa** [comment]
I was meaning something like:
`ors_geocode("Heidelberg", boundary.country = c("DE", "AT", "IT", "US", "GB", "CH"))`

**Comment by aoles** [comment]
Hi Bartosz,

multiple countries can be specified in a comma separated character string like so:

```
ors_geocode("Heidelberg", boundary.country = "DE,US")
```

Cheers,
Andrzej
