### ISSUE TITLE
Error in request(headers = c(..., .headers)) :    is.character(headers) is not TRUE

### ISSUE THREAD

**Issue by DJSUBHAOO7** [GIScience/openrouteservice-r#62]
coordinates <- data.frame(lat=c(8.34234, 8.34423),lon=c(48.23424, 48.26424))
route<-ors_directions(coordinates, profile = ors_profile(mode="walking"),
                      format ="geojson",api_key =api,
                      output = "sf")

Can you please help me to put the header ?

**Comment by aoles** [comment]
Once you set your api key for the first time time via a standalone call to `ors_api_key` as described [here](https://giscience.github.io/openrouteservice-r/articles/openrouteservice.html#setting-up-api-key) you don't need to include the `api_key` argument to `ors_directions` unless you want to use a different key from the one previously set. Try the following:

```r
ors_api_key("<your-api-key>")

coordinates <- data.frame(lat=c(8.34234, 8.34423), lon=c(48.23424, 48.26424))

route <- ors_directions(coordinates, profile = ors_profile("walking"), 
                        format = "geojson", output = "sf")
```

**Comment by DJSUBHAOO7** [comment]
route<-ors_directions(list(c(23.43219, 88.30757), c(22.43199, 87.29786)))
leaflet() %>%
  addTiles() %>%
  addGeoJSON(route, fill=FALSE) %>%
  fitBBox(route$bbox)


Error: Openrouteservice API request failed
[2010] Could not find point 0: 23.4321900 88.3075700 within a radius of 350.0 meters.

How to get directions over 350 meters ?

**Comment by aoles** [comment]
As indicated by the error message, the problem you are experiencing is that the [provided  coordinates](https://www.openstreetmap.org/search?query=23.43219%2C%2088.30757#map=15/23.4322/88.3076&layers=H) correspond to a point which is located by more than 350m away from a street mapped in OSM. Try with coordinates closer to existing OSM ways.

**Comment by DJSUBHAOO7** [comment]
how I can add a search radius for that type of case in r? like I found this : {"coordinates":[[-122.4889283,38.5192598],[-122.32358,38.41810]],"radiuses":[350,500]}

**Comment by aoles** [comment]
Please note that the coordinates provided to `ors_directions` are ordered as **longitude**, **latitude** pairs, so first of all you need to swap the values around. Regarding increasing the search radius, you can do it like so:

```r
route <- ors_directions(list(c(88.30757, 23.43219), c(87.29786, 22.43199)),
                        radiuses = c(1000, 1000))
```
