### ISSUE TITLE
Question : Custom matrix 

### ISSUE THREAD

**Issue by chalioui** [GIScience/openrouteservice-r#68]
Hi there ! Thank you for this great project! 
Can you give us an example of using optimization function with a custom matrix ?

**Comment by aoles** [comment]
Hi, 

thanks for reaching out! Actually, there seem to be some problem with providing a custom matrix to `ors_optimization`. I will look into this issue and get back to you as soon as I know more.

Cheers,
Andrzej

**Comment by chalioui** [comment]
Hi!
I have found an alternative solution .
I am using the jsonlite toJSON function : 
```
# convert the matrix p to json 
p1 <- toJSON(p)



res <- httr::POST(
  url = "http://localhost:3000/",
  httr::add_headers(c("Content-Type" = "application/json")),
  
  body = glue::glue('{
  "vehicles": [
    {
      "id":0,
      "start_index":0,
      "end_index":3
    }
  ],
  "jobs": [
    {
      "id":1414,
      "location_index":1
    },
    {
      "id":1515,
      "location_index":2
    }
  ],
  "matrix": <<p1>>
}', .open = "<<", .close = ">>"),
  encode = "json"
)
```

**Comment by aoles** [comment]
Thanks for your feedback!

Actually, the package already supports custom cost matrix, so there is no need of constructing the request yourself and calling it via `httr::POST`. Based on the provided example the public openrouteservice optimization API can be queried as follows.

```r
library(openrouteservice)

m <- matrix(data = c(0, 2104, 197, 1299,
                    2103, 0, 2255, 3152,
                    197, 2256, 0, 1102,
                    1299, 3153, 1102, 0), nrow = 4, ncol = 4, byrow = TRUE)

vehicles <- vehicles(
  id = 0,
  profile = "driving-car",
  start_index = 0,
  end_index = 3
)

jobs <- jobs(
  id = c(1414, 1515),
  location_index = 1:2
)

res <- ors_optimization(jobs, vehicles, matrix = m)
```

**Comment by chalioui** [comment]
Thank you!
