### ISSUE TITLE
Matrix: Use POST, not GET

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice-r#7]
GET has limited amount of characters, which is can limit the usability esp for matrix API. Also, did you constrain coordinate input to 6 decimals? Couldn't really decipher that, but didn't look like it. If not, please do that, too.

**Comment by aoles** [comment]
Thanks Nils, I will switch the method for the matrix endpoint from GET to POST.

Re constraining the coordinates, how is this handled internally by the ORS API - is there any reduction performed, or are coordinates of arbitrary precision allowed? (CC @TimMcCauley @rabidllama @HendrikLeuschner)

**Comment by TimMcCauley** [comment]
Any work, they are trimmed internally afaik, just give it a quick try.

**Comment by aoles** [comment]
As of [v 0.1.3](https://github.com/GIScience/openrouteservice-r/commit/c28f063) all numeric parameters such as coordinates are rounded to 6 decimal places.
