### ISSUE TITLE
ORS_Matrix 503 error

### ISSUE THREAD

**Issue by elliec** [GIScience/openrouteservice-r#70]
Hi, I have been running a script using ors_matrix to calculate foot-walking distance and driving-car distance between a house a two shops. It worked fine yesterday but i have run it again today and foot-walking works without a problem but driving-car fails with the following error: Error: Service Unavailable (HTTP 503). is it something I am doing? I moved the location of one of the shops but it shouldn't cause an issue with driving, it is still on a road.

below are my points and code

thanks!

         X         Y
 115.7963 -31.79458
 115.8132 -31.84368
 115.7945 -31.79879

#query for duration and distance in meters for walking - works
res = ors_matrix(df_mb, sources=c(0:0), metrics = c("duration", "distance"), profile="foot-walking", units = "m")

#calculate and save results of car travel - fails
res = ors_matrix(df_mb, sources=c(0:0), metrics = c("duration", "distance"),  units = "m")

**Comment by aoles** [comment]
Hi, Thanks for your feedback! 

It must have been a transient network issue as your sample query seems to work now.

```r
library(openrouteservice)

coordinates = list(
  c(115.7963, -31.79458),
  c(115.8132, -31.84368),
  c(115.7945, -31.79879)
)

metrics = c("duration", "distance")

#query for duration and distance in meters for walking
res = ors_matrix(coordinates, sources = 0, metrics = metrics, profile = "foot-walking")

#calculate and save results of car travel
res = ors_matrix(coordinates, sources = 0, metrics = metrics)
```

Please note that it is fine to provide just a single value to `sources` and specifying `units = "m"` is redundant as this is the default anyway.

Cheers!

**Comment by elliec** [comment]
Hi Aoles,

Thanks so much for getting back to me! it seems to be working fine now. and thanks also for your helpful comments :)

Could you explain what you mean by providing a single value to sources? can i provide them as a seperate df? I had a few issues setting sources and that was what i managed to get working.

Ellie

**Comment by elliec** [comment]
I understand what you mean now - thanks for pointing it out!
