### ISSUE TITLE
Can't install package from DESCRIPTION file with PAK

### ISSUE THREAD

**Issue by pascalgulikers** [GIScience/openrouteservice-r#78]
Hello, we're using PAK als our R package dependency solver.
No matter what I try, I can't get openrouteservice package installed.

For example:

```
Depends:
  openrouteservice=github::/GIScience/openrouteservice
```

Results in:

```
pak::pkg_install("~/test")
Error:                                                                                            
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* local::~/test: Can't install dependency openrouteservice=github::GIScience/openrouteservice-r
Type .Last.error to see the more details.
```

See: https://pak.r-lib.org/reference/pak_package_sources.html
Is there a working example for how to implement openrouteservice as a dependency in a package (e.g. DESCRIPTION file)?

**Comment by aoles** [comment]
Thanks for reaching out!

I'm not entirely familiar with PAK, but according to the [docs](https://pak.r-lib.org/reference/pak_package_sources.html#package-names), you might want to try sth along the lines: 

```
openrouteservice=github::GIScience/openrouteservice-r
```

Please let me know whether the above syntax resolved your dependency issue. Cheers!

**Comment by pascalgulikers** [comment]
Solved
