### ISSUE TITLE
Dependency geojsonlint is deprecated which fails openrouteservice install

### ISSUE THREAD

**Issue by pascalgulikers** [GIScience/openrouteservice-r#79]
https://packagemanager.posit.co/client/#/repos/2/packages/geojsonlint has been archived.
Because of this installing openrouteservice fails

**Comment by BobVanDiest** [comment]
Is there going to be a solution for this issue? We are still unable to install openrouteservice

**Comment by aoles** [comment]
Hi @pascalgulikers, @BobVanDiest,

Thanks a lot for your feedback!

I've been away on vacation, and  this issue went a under my radar 🙈  I will look into it, so please stay tuned.

Cheers!
Andrzej
