### ISSUE TITLE
Add optional parameters for all endpoints

### ISSUE THREAD

**Issue by nilsnolde** [GIScience/openrouteservice-r#8]
The API is way to generic. None of our custom, optional parameters are available except for the required ones. Please add ALL parameters to ALL endpoints.

**Comment by aoles** [comment]
For the record, any missing optional parameters to any of the endpoints can be provided in the ellipsis argument `...`, as illustrated by the [example](https://github.com/GIScience/openrouteservice-r/issues/6#issuecomment-383889779).
