### ISSUE TITLE
Installation fails (Ubuntu 20.04.6 LTS)

### ISSUE THREAD

**Issue by viajerus** [GIScience/openrouteservice-r#80]
I've been trying to install openrouteservice-r and it fails. It also fails if I use a fresh R session. 
About my environment: I am using the latest [rocker/geospatial](https://hub.docker.com/r/rocker/geospatial) image, which uses R 4.3.1. Never had any problems before.

![image](https://github.com/user-attachments/assets/f4b187f3-f414-4da8-b77a-ad4eb9ec1345)

Best, 
Daniel

**Comment by mmoralesIG** [comment]
Hi, here using 4.4.0 and previously 4.3.2 in Windows. I installed it using remotes having no issues as far as I recall
`remotes::install_github("GIScience/openrouteservice-r")`

**Comment by aoles** [comment]
Hi Daniel,

thanks for reaching out! ❤️ 

The reason for the observed error is a missing system library for the keyring package to work, which is one of openrouteservice R package dependencies. The missing system package is libsecret-1-dev.

Please try the following approach to install R packages automagically with all the necessary system dependencies.

```r
install.packages("pak")
pak::pak("GIScience/openrouteservice-r")
```

Cheers,
Andrzej

**Comment by viajerus** [comment]
Hi Andrzej, 
the installation with pak worked before, but I had to install the library keyring before, also with pak. 

```
pak::pak("r-lib/keyring")
```
and then 

```
pak::pak("GIScience/openrouteservice-r")
```
