### ISSUE TITLE
Error in rbind(deparse.level, …) 

### ISSUE THREAD

**Issue by mmoralesIG** [GIScience/openrouteservice-r#81]
Hi, 

I'm having a problem in R trying to get the POI inside a box, so I can pass them as markers (add_markers) 

```
ors_pois(geometry =
list(bbox = list(c(-90.5158552, 14.6012396), c(-90.51270092658864,14.596370217083651)),
buffer = 100) ,
limit = 100,
request = c(“pois”),
output = “sf”,
filters = list(category_group_ids = 560)
)
```
But I'm getting an “Error in rbind(deparse.level, …) : numbers of columns of arguments do not match”

It was mentioned an possible issue with the `output = "sf"`

Thank you for your help.

**Comment by aoles** [comment]
Thanks for filing the bug report. I will look into it and get back to you soon. Cheers!

**Comment by mmoralesIG** [comment]
Thank you, So far is working! :D
